baseURL = "https://a-writes-code.github.io/"
languageCode = "en-us"
title = "Aritra Das"
theme = "toha"

enableEmoji = true
enableGitInfo = true

[outputs]
home = ["HTML", "RSS", "JSON"]

[module]
  [[module.imports]]
    path = "github.com/hugo-toha/toha/v4"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  background = "images/background.jpg"

[params.features]
  search = false

